FROM openjdk:22
#COPY pom.xml /tmp/
#COPY src /tmp/src/
WORKDIR /tmp/
RUN mkdir -p /tmp/Wallet_CHATBOT
COPY Wallet_CHATBOT /tmp/Wallet_CHATBOT
ENV db_url="jdbc:oracle:thin:@chatbot_high?TNS_ADMIN=/tmp/Wallet_CHATBOT"
ENV db_user="TODOUSER"
ENV dbpassword="Pokemon12345"
EXPOSE 8080
COPY target/MyTodoList-0.0.1-SNAPSHOT.jar MyTodoList.jar
ENTRYPOINT ["java","-jar","MyTodoList.jar"]